### ISSUE TITLE
docker方式启动，报错404

### ISSUE THREAD

**Issue by linyqh** [Geniucker/Deploy-ChatGPT-to-API#1]
- 使用docker启动，在sider设置完成，报404
```
# docker logs -f chatgpttoapi
[INFO]Get access token of xxxxxxxx successfully.
[INFO]2023/06/06 16:12:27 7 0.0.0.0:8080
[WARNING][GIN] 2023/06/06 - 16:12:47 | 404 |     107.146µs |    192.168.10.5 | GET      "/v1/models"
```
![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/45776646/d5a6e585-0ce5-45b7-b225-6dc6da251eb7)

**Comment by Geniucker** [comment]
/v1/models确实是一个没有模拟的API，原作者只模拟了completions，所以sider无法获取模型列表，这个要是要改得去原项目改
所以sider可能切不了模型
