### ISSUE TITLE
openai translator插件问题

### ISSUE THREAD

**Issue by AlterGu** [Geniucker/Deploy-ChatGPT-to-API#3]
你好，想问下在openai translator中设置了自建api的url后，在翻译时没有返回结果，是模型选择的问题还是其它什么问题吗？
![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/39581263/8246fad7-2684-4990-a730-bb9944e56fb7)
![image](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/39581263/25e74f49-c9d7-4eb3-8222-baf294b54c63)

**Comment by AlterGu** [comment]
sider的确可以正常使用，行吧先用sider替代openai translator了。

**Comment by Geniucker** [comment]
@AlterGu 原项目已修复这个问题，你git pull然后重新build一次就可以用了

**Comment by AlterGu** [comment]
感谢提醒，已更新正常使用。
