### ISSUE TITLE
前面的404不知道是什么，/v1/chat/completions虽然是报的200，但是没有响应的回复

### ISSUE THREAD

**Issue by JzeroM** [Geniucker/Deploy-ChatGPT-to-API#4]
root@fantasy:/Deploy-ChatGPT-to-API# docker logs chatgpttoapi
[INFO]Get access token of jzerom@proton.me successfully.
[INFO]Get access token of jzerom2@proton.me successfully.
[INFO]Get access token of jzerom3@proton.me successfully.
[INFO]Get access token of jzerom4@proton.me successfully.
[INFO]Get access token of jzerom5@proton.me successfully.
[INFO]2023/07/01 18:37:30 8 0.0.0.0:8080
[WARNING][GIN] 2023/07/01 - 18:40:10 | 404 |      23.777µs |   114.216.69.24 | OPTIONS  "/dashboard/billing/subscription"
[WARNING][GIN] 2023/07/01 - 18:40:10 | 404 |       6.946µs |   114.216.69.24 | OPTIONS  "/dashboard/billing/usage"
[INFO][GIN] 2023/07/01 - 18:40:22 | 200 |     592.617µs |   114.216.69.24 | OPTIONS  "/v1/chat/completions"

**Comment by JzeroM** [comment]
不填custom_API_key就是上述问题，填上，第三方插件也必须填

**Comment by Geniucker** [comment]
已修复，git pull之后重新build一次试试

**Comment by Geniucker** [comment]
前面的404是因为网页版没法获取用量情况，所以原项目没有实现这个接口，也没有实现的意义，对于使用没有影响
顺便一提的是，虽然你看到控制台里出来了200，但是这个200是OPTIONS请求，实际有用的是发给/v1/chat/completions的POST请求，这个请求因为一个bug被拦下来了，所以真正的chatgpt-to-api后端其实没有拿到这个请求
