### ISSUE TITLE
并发问题

### ISSUE THREAD

**Issue by 848150331** [Geniucker/Deploy-ChatGPT-to-API#9]
添加了多个账号，也无法并发同时请求吗？

**Comment by Geniucker** [comment]
应该是可以的

**Comment by 848150331** [comment]
我这边本地部署，添加了多个账号，只能等待上一个请求完成才会请求下一个
![python](https://github.com/Geniucker/Deploy-ChatGPT-to-API/assets/49086826/a11a60ac-68ee-4db7-9a4f-d97872a5e0de)

**Comment by Geniucker** [comment]
@848150331 这个日志是一次请求结束才显示的，所以日志先后显示不能判断有没有处理并发的请求

**Comment by 848150331** [comment]
谢谢，搞半天原来是web项目的问题导致的。。。
